version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./agency_backend:/app/agency_backend
      - ./app.db:/app/app.db
      - ./contracts:/app/contracts
      - ./static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn agency_backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./agency_frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge