version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agency_backend
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./agency_backend/static:/app/static
      - ./agency_backend/contracts:/app/contracts
      - ./agency_backend/files:/app/files
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:////data/app.db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agency_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local