version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    env_file: .env.production
    expose:
      - "8000"
    volumes:
      - ./data:/data
      - ./contracts:/app/contracts
      - ./static:/app/static
    command: uvicorn agency_backend.app.main:app --host 0.0.0.0 --port 8000 --workers 2
    restart: unless-stopped
    networks: [app-net]

  frontend-build:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    env_file: agency_frontend/.env.production
    command: sh -c "npm ci && npm run build"
    volumes:
      - ./agency_frontend:/app
      - ./dist:/app/dist
    networks: [app-net]

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-build
    restart: unless-stopped
    networks: [app-net]

networks:
  app-net:
    driver: bridge
